stages:
  - build

build:
  image: node:14-alpine
  stage: build
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test
    - npm run build
  artifacts:
    expire_in: 2 weeks
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}'
    paths:
      - dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
