stages:
  - build
  - publish

build:
  image: node:14-alpine
  stage: build
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test
    - npm run build
  artifacts:
    expire_in: 2 weeks
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}'
    paths:
      - dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

publish:
  stage: publish
  image: node:14-alpine
  script:
    - '[[ -z $NPM_TOKEN ]] && exit 1'
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - npm publish --access public
  only:
    - /^(0|[1-9]\d*)\.(0|[1-9≥]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/